# Generated by Django 3.2.8 on 2021-10-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author_birth_year',
            field=models.PositiveIntegerField(verbose_name='Год рождения автора'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_written_year',
            field=models.PositiveIntegerField(verbose_name='Год издания книги'),
        ),
    ]
