# Generated by Django 3.2.8 on 2021-10-26 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20211026_0844'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('author', 'book_title')},
        ),
    ]
