# Generated by Django 3.2.8 on 2021-10-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=124, unique=True, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_title',
            field=models.CharField(db_index=True, max_length=124, unique=True, verbose_name='Название книги'),
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together=set(),
        ),
    ]
